# -*- coding: utf-8 -*-
"""MLCS_Exp7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sT6OZH_zttZa8zOaxpdfZz6dcc8ZO-K
"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
from urllib.parse import urlparse
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv("/content/dataset_with_all_features v2.csv")

df = df.rename(columns={'type': 'label'})

df = df.dropna(subset=['url', 'label'])

print(df.columns)
df.head()

df = df.loc[:, ~df.columns.duplicated()]

if 'type' in df.columns:
    df = df.drop(columns=['label'], errors='ignore')
    df = df.rename(columns={'type': 'label'})

df['label'] = df['label'].astype(str).str.strip().str.lower()

df['label'] = df['label'].replace({
    'benign': 0,
    'phishing': 1,
    'malware': 1,
    'defacement': 1
})

df = df[df['label'].isin([0, 1])]

print(df['label'].value_counts())

X = df.drop(columns=['url', 'label', 'Date_inspection'], errors='ignore')

X = X.select_dtypes(include=[np.number])

y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

importances = model.feature_importances_
feature_names = X.columns

indices = np.argsort(importances)[-20:]

plt.figure(figsize=(10,6))
plt.barh(range(len(indices)), importances[indices])
plt.yticks(range(len(indices)), [feature_names[i] for i in indices])
plt.title("Top 20 Important Features")
plt.xlabel("Importance")
plt.show()

def predict_sample(sample_row):
    sample = np.array(sample_row).reshape(1, -1)
    pred = model.predict(sample)[0]
    return "Malicious" if pred == 1 else "Safe"

sample = X.iloc[1].values
print("\nSample Prediction:", predict_sample(sample))